services:

  app:
    build:
      context: .
      dockerfile: docker/8.2/Dockerfile

    container_name: simaik-app
    restart: unless-stopped

    working_dir: /var/www/html

    environment:
      TZ: Asia/Jakarta

    volumes:
      - ./:/var/www/html

    networks:
      - proxy-manager


  nginx:
    image: nginx:alpine
    container_name: simaik-nginx
    restart: unless-stopped

    depends_on:
      - app

    volumes:
      - ./:/var/www/html:ro
      - ./nginx:/etc/nginx/conf.d:ro

    networks:
      - proxy-manager


networks:
  proxy-manager:
    external: true