services:

  app:
    build:
      context: .
      dockerfile: docker/8.2/Dockerfile

    container_name: simaik-app
    restart: unless-stopped

    working_dir: /var/www/html

    environment:
      TZ: Asia/Jakarta

    volumes:
      - ./:/var/www/html

    networks:
      - akbidw_app-network


  nginx:
    image: nginx:alpine
    container_name: simaik-nginx
    restart: unless-stopped

    security_opt:
      - seccomp=unconfined

    volumes:
      - /home/ummetro.simaik/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/ummetro.simaik/nginx:/etc/nginx/conf.d:ro
      - /home/ummetro.simaik:/var/www/html:ro

    networks:
      - akbidw_app-network


networks:
  akbidw_app-network:
    external: true