<?php
// Variables
return [
  'creatorName' => 'Pusat Teknologi Informasi dan Komunikasi',
  'creatorUrl' => 'https://pustik.ummetro.ac.id',
  'templateName' => 'SIM AIK UM METRO',
  'templateSuffix' => 'SISTEM INFORMASI AL-ISLAM DAN KEMUHAMMADIYAHAN',
  'templateVersion' => '1.0.0',
  'templateFree' => false,
  'templateDescription' => 'Sistem Informasi Akademik Universitas Muhammadiyah Metro',
  'templateKeyword' => 'siakad, kampus merdeka, mbkm, siakad mbkm, ummetro',
  'licenseUrl' => '#',
  'livePreview' => '#',
  'productPage' => '#',
  'support' => '#',
  'moreThemes' => '#',
  'documentation' => '#',
  'generator' => '',
  'changelog' => '#',
  'repository' => '#',
  'gitRepo' => 'pixinvent',
  'gitRepoAccess' => 'vuexy-html-admin-template',
  'githubFreeUrl' => 'https://tools.pixinvent.com/github/github-access',
  'facebookUrl' => 'https://www.facebook.com/pixinvents/',
  'twitterUrl' => 'https://twitter.com/pixinvents',
  'githubUrl' => 'https://github.com/pixinvent',
  'dribbbleUrl' => 'https://dribbble.com/pixinvent',
  'instagramUrl' => 'https://www.instagram.com/pixinvents/',
];
